<link rel="stylesheet" href="assets/front_end/css/perfil.css">
<script type="text/javascript" src="assets/front_end/js/perfil.js"></script>

<br><br><br><br><br><br>
<div class="ui container">
    <img id="borda" class="ui centered small circular image" src="assets/files/img/lazinha.jpg">
    <div class="ui top attached tabular menu">
        <a id="perfil" class="active item">
            Perfil
        </a>
        <a id="graficos" class="item">
            Gráficos
        </a>
        <a id="seguidores" class="item">
            Seguidores
        </a>
        <a  id="seguindo" class="item">
            Seguindo
        </a>
        <a id="editar" class="item">
            Editar
        </a>
    </div>
    <div class="ui bottom attached segment">
        <div id="conteudo">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate, tortor quis feugiat convallis, turpis justo mollis magna, eu porta lorem metus vitae nunc. Phasellus fermentum nulla sit amet pellentesque malesuada. In tempor tortor ac lobortis pharetra. Integer augue nibh, tempor eu dui sit amet, vulputate vehicula risus. Ut elementum facilisis tristique. Praesent dignissim odio quis leo faucibus, quis convallis sapien commodo. Fusce fringilla, turpis a viverra volutpat, nisi quam tincidunt turpis, et iaculis metus arcu ac felis.
                e nisl sodales urna accumsan,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate, tortor quis feugiat convallis, turpis justo mollis magna, eu porta lorem metus vitae nunc. Phasellus fermentum nulla sit amet pellentesque malesuada. In tempor tortor ac lobortis pharetra. Integer augue nibh, tempor eu dui sit amet, vulputate vehicula risus. Ut elementum facilisis tristique. Praesent dignissim odio quis leo faucibus, quis convallis sapien commodo. Fusce fringilla, turpis a viverra volutpat, nisi quam tincidunt turpis, et iaculis metus arcu ac felis.
                e nisl sodales urna accumsan,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate, tortor quis feugiat convallis, turpis justo mollis magna, eu porta lorem metus vitae nunc. Phasellus fermentum nulla sit amet pellentesque malesuada. In tempor tortor ac lobortis pharetra. Integer augue nibh, tempor eu dui sit amet, vulputate vehicula risus. Ut elementum facilisis tristique. Praesent dignissim odio quis leo faucibus, quis convallis sapien commodo. Fusce fringilla, turpis a viverra volutpat, nisi quam tincidunt turpis, et iaculis metus arcu ac felis.
                e nisl sodales urna accumsan,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate, tortor quis feugiat convallis, turpis justo mollis magna, eu porta lorem metus vitae nunc. Phasellus fermentum nulla sit amet pellentesque malesuada. In tempor tortor ac lobortis pharetra. Integer augue nibh, tempor eu dui sit amet, vulputate vehicula risus. Ut elementum facilisis tristique. Praesent dignissim odio quis leo faucibus, quis convallis sapien commodo. Fusce fringilla, turpis a viverra volutpat, nisi quam tincidunt turpis, et iaculis metus arcu ac felis.
                e nisl sodales urna accumsan,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate, tortor quis feugiat convallis, turpis justo mollis magna, eu porta lorem metus vitae nunc. Phasellus fermentum nulla sit amet pellentesque malesuada. In tempor tortor ac lobortis pharetra. Integer augue nibh, tempor eu dui sit amet, vulputate vehicula risus. Ut elementum facilisis tristique. Praesent dignissim odio quis leo faucibus, quis convallis sapien commodo. Fusce fringilla, turpis a viverra volutpat, nisi quam tincidunt turpis, et iaculis metus arcu ac felis.
                e nisl sodales urna accumsan,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate, tortor quis feugiat convallis, turpis justo mollis magna, eu porta lorem metus vitae nunc. Phasellus fermentum nulla sit amet pellentesque malesuada. In tempor tortor ac lobortis pharetra. Integer augue nibh, tempor eu dui sit amet, vulputate vehicula risus. Ut elementum facilisis tristique. Praesent dignissim odio quis leo faucibus, quis convallis sapien commodo. Fusce fringilla, turpis a viverra volutpat, nisi quam tincidunt turpis, et iaculis metus arcu ac felis.
                e nisl sodales urna accumsan,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspeles urna accumsan,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate, tortor quis feugiat convallis, turpis justo mollis magna, eu porta lorem metus vitae nunc. Phasellus fermentum nulla sit amet pellentesque malesuada. In tempor tortor ac lobortis pharetra. Integer augue nibh, tempor eu dui sit amet, vulputate vehicula risus. Ut elementum facilisis tristique. Praesent dignissim odio quis leo faucibus, quis convallis sapien commodo. Fusce fringilla, turpis a viverra volutpat, nisi quam tincidunt turpis, et iaculis metus arcu ac felis.
                e nisl sodales urna accumsan,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate, tortor quis feugiat convallis, turpis justo mollis magna, eu porta lorem metus vitae nunc. Phasellus fermentum nulla sit amet pellentesque malesuada. In tempor tortor ac lobortis pharetra. Integer augue nibh, tempor eu dui sit amet, vulputate vehicula risus. Ut elementum facilisis tristique. Praesent dignissim odio quis leo faucibus, quis convallis sapien commodo. Fusce fringilla, turpis a viverra volutpat, nisi quam tincidunt turpis, et iaculis metus arcu ac felis.
                e nisl sodales urna accumsan,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate, tortor quis feugiat convallis, turpis justo mollis magna, eu porta lorem metus vitae nunc. Phasellus fermentum nulla sit amet pellentesque malesuada. In tempor tortor ac lobortis pharetra. Integer augue nibh, tempor eu dui sit amet, vulputate vehicula risus. Ut elementum facilisis tristique. Praesent dignissim odio quis leo faucibus, quis convallis sapien commodo. Fusce fringilla, turpis a viverra volutpat, nisi quam tincidunt turpis, et iaculis metus arcu ac felis.
                e nisl sodales urna accumsan,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate, tortor quis feugiat convallis, turpis justo mollis magna, eu porta lorem metus vitae nunc. Phasellus fermentum nulla sit amet pellentesque malesuada. In tempor tortor ac lobortis pharetra. Integer augue nibh, tempor eu dui sit amet, vulputate vehicula risus. Ut elementum facilisis tristique. Praesent dignissim odio quis leo faucibus, quis convallis sapien commodo. Fusce fringilla, turpis a viverra volutpat, nisi quam tincidunt turpis, et iaculis metus arcu ac felis.
                e nisl sodales urna accumsan,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspeles urna accumsan,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate, tortor quis feugiat convallis, turpis justo mollis magna, eu porta lorem metus vitae nunc. Phasellus fermentum nulla sit amet pellentesque malesuada. In tempor tortor ac lobortis pharetra. Integer augue nibh, tempor eu dui sit amet, vulputate vehicula risus. Ut elementum facilisis tristique. Praesent dignissim odio quis leo faucibus, quis convallis sapien commodo. Fusce fringilla, turpis a viverra volutpat, nisi quam tincidunt turpis, et iaculis metus arcu ac felis.
                e nisl sodales urna accumsan,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate, tortor quis feugiat convallis, turpis justo mollis magna, eu porta lorem metus vitae nunc. Phasellus fermentum nulla sit amet pellentesque malesuada. In tempor tortor ac lobortis pharetra. Integer augue nibh, tempor eu dui sit amet, vulputate vehicula risus. Ut elementum facilisis tristique. Praesent dignissim odio quis leo faucibus, quis convallis sapien commodo. Fusce fringilla, turpis a viverra volutpat, nisi quam tincidunt turpis, et iaculis metus arcu ac felis.
                e nisl sodales urna accumsan,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate, tortor quis feugiat convallis, turpis justo mollis magna, eu porta lorem metus vitae nunc. Phasellus fermentum nulla sit amet pellentesque malesuada. In tempor tortor ac lobortis pharetra. Integer augue nibh, tempor eu dui sit amet, vulputate vehicula risus. Ut elementum facilisis tristique. Praesent dignissim odio quis leo faucibus, quis convallis sapien commodo. Fusce fringilla, turpis a viverra volutpat, nisi quam tincidunt turpis, et iaculis metus arcu ac felis.
                e nisl sodales urna accumsan,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate, tortor quis feugiat convallis, turpis justo mollis magna, eu porta lorem metus vitae nunc. Phasellus fermentum nulla sit amet pellentesque malesuada. In tempor tortor ac lobortis pharetra. Integer augue nibh, tempor eu dui sit amet, vulputate vehicula risus. Ut elementum facilisis tristique. Praesent dignissim odio quis leo faucibus, quis convallis sapien commodo. Fusce fringilla, turpis a viverra volutpat, nisi quam tincidunt turpis, et iaculis metus arcu ac felis.
                e nisl sodales urna accumsan,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate, tortor quis feugiat convallis, turpis justo mollis magna, eu porta lorem metus vitae nunc. Phasellus fermentum nulla sit amet pellentesque malesuada. In tempor tortor ac lobortis pharetra. Integer augue nibh, tempor eu dui sit amet, vulputate vehicula risus. Ut elementum facilisis tristique. Praesent dignissim odio quis leo faucibus, quis convallis sapien commodo. Fusce fringilla, turpis a viverra volutpat, nisi quam tincidunt turpis, et iaculis metus arcu ac felis.
                e nisl sodales urna accumsan, at placerat risus tempus. Curabitur dignissim massa metus, et fringilla libero pretium id. Maecenas massa nunc, facilisis at ex in, tempor fermentum erat. Sed elementum arcu et nulla viverra luctus. Cras faucibus est at augue aliquam iaculis. Praesent molestie felis id risus iaculis, eget lobortis diam dictum. Sed malesuada massa ut metus semper, vel tristique velit facilisis. Maecenas mattis diam eu ante fermentum suscipit.</p>

            </p>
        </div>
    </div>


    <!--<img class="ui small circular image" src="assets/files/img/lazinha.jpg" style="position: absolute; margin-left: 43.15%; margin-top: -7.5%; border: 2px; border-co
">-->
</div>

<br>